[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "0xb77ee0"
text = "0x000000"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 18.0

[font.bold]
# family = "Lekton Nerd Font"
# family = "FantasqueSansMono Nerd Font"
family = "VictorMono Nerd Font"
# family = "Iosevka Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
# family = "Lekton Nerd Font"
# family = "FantasqueSansMono Nerd Font"
family = "VictorMono Nerd Font"
# family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
# family = "Lekton Nerd Font"
# family = "FantasqueSansMono Nerd Font"
family = "VictorMono Nerd Font"
# family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>¬"

[window]
dynamic_title = true
opacity = 1

[window.dimensions]
columns = 96
lines = 32

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
import = ["~/.config/alacritty/colors.toml"]
