# Configuration for Alacritty, the GPU enhanced terminal emulator
env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 96
    lines: 32
  padding:
    x: 2
    y: 2
  decorations: none

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: &family VictorMono Nerd Font
    style: Regular
  bold:
    family: *family
    style: Bold
  italic:
    family: *family
    style: Italic
  size: 14.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: true

custom_cursor_colors: true

colors:
  cursor:
    text: '0x000000'
    cursor: '0xb77ee0'

background_opacity: 1.0

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

dynamic_title: true
cursor:
  style: Block

live_config_reload: true

key_bindings:
  - { key: N,   mods: Control|Shift, action: SpawnNewInstance }
  - { key: F11,                      action: ToggleFullscreen }
