---
version: '3.8'
services:
  dev:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - UID=$UID
        - GID=$GID
        - USERNAME=$USERNAME
    cap_add:
      - ALL
    env_file:
      # Absolute or relative path to the secrets file on your local machine
      - ../.secrets.local
    environment:
      - DATABASE_HOSTNAME=postgresql
      - DB_USERNAME=postgres
      - NODE_EXTRA_CA_CERTS=/etc/ca-certificates/trust-source/anchors/GNSServicesCA.crt
      - NPM_CONFIG_CACHE=/opt/node/.npm
      - NPM_CONFIG_STRICT_SSL=false
      - NVM_DIR=/opt/node/.nvm
      - RBENV_ROOT=/opt/rbenv
    volumes:
      - dev-data:/home/$USERNAME/projects
      - npm-cache:/opt/node
      - ruby-cache:/opt/rbenv
      - ../.git-credential-store:/home/$USERNAME/.git-credential-store
      - ../.credentials:/home/$USERNAME/.credentials
      - ../.ssh:/home/$USERNAME/.ssh
      - ../.gnupg:/home/$USERNAME/.gnupg
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # ports:
    #   - 3000-3030:3000-3030
    #   - 5000-5050:5000-5050
    network_mode: host
    # networks:
    #   # - overlay
    #   hostnet: {}
    user: $USERNAME

volumes:
  dev-data:
    external: true
  ruby-cache:
  npm-cache:

networks:
  overlay:
    external: true
  hostnet:
    external: true
    name: host
