" Use Vim settings, rather then Vi settings. This setting must be as early as
" possible, as it has side effects.
set nocompatible

" Leader
let mapleader = " "

set encoding=utf-8
set backspace=2   " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set noswapfile    " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if (&t_Co > 2 || has("gui_running")) && !exists("syntax_on")
  syntax on
endif

if filereadable(expand("~/.vim/vimrc.bundles"))
  source ~/.vim/vimrc.bundles
endif

filetype plugin indent on

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" Enable code folding but don't fold up
set foldlevel=25
set foldmethod=syntax

augroup vimrcEx
  autocmd!

  " When editing a file, always jump to the last known cursor position.
  " Don't do it for commit messages, when the position is invalid, or when
  " inside an event handler (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

  " Set syntax highlighting for specific file types
  autocmd BufRead,BufNewFile Appraisals set filetype=ruby
  autocmd BufRead,BufNewFile *.md set filetype=markdown
  autocmd BufRead,BufNewFile *.es6 set filetype=javascript
  autocmd BufRead,BufNewFile .jshintrc set filetype=json
  autocmd BufRead,BufNewFile *.inky set filetype=eruby.html
  " autocmd BufRead,BufNewFile *.svelte set filetype=html

  " Enable spellchecking for Markdown
  autocmd FileType markdown,text setlocal spell

  " Disable hidden quotes in JSON
  autocmd FileType json setlocal cole=0

  " Automatically wrap at 80 characters for Markdown
  autocmd BufRead,BufNewFile *.md setlocal textwidth=80

  " Automatically wrap at 72 characters for git commit messages
  autocmd FileType gitcommit setlocal textwidth=72

  " Allow stylesheets to autocomplete hyphenated words
  autocmd FileType css,scss,sass setlocal iskeyword+=-

  autocmd FileType yaml setlocal foldmethod=indent
  " Set JS to indent at 4 spaces
  " autocmd FileType javascript,js setlocal tabstop=4 shiftwidth=4
augroup END

let g:indentLine_fileTypeExclude = ['markdown', 'json']
let g:indentLine_char_list = ['|', '¦', '┆', '┊']
let g:indentLine_faster = 1
let g:indentLine_leadingSpaceChar = '·'

" Color scheme
set t_Co=256
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
  highlight Comment cterm=italic gui=italic
endif
set t_ZH=[3m
set t_ZR=[23m

" Airline Customization
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#right_sep     = ''
let g:airline#extensions#tabline#right_alt_sep = ''
let g:airline#extensions#tabline#left_sep      = ''
let g:airline#extensions#tabline#left_alt_sep  = ''
let g:airline_right_sep     = ''
let g:airline_right_alt_sep = ''
let g:airline_left_sep      = ''
let g:airline_left_alt_sep  = ''

let g:airline_theme = 'base16'
let g:airline_powerline_fonts = 1

" Numbers
set number
set numberwidth=5

" Disable syntax highlighting after the first 200 columns
" (speeds up vim when super long lines are present)
set synmaxcol=200

" Tab completion
" will insert tab at beginning of line,
" will use completion if not at beginning
set wildmode=list:longest,list:full
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<tab>"
    else
        return "\<c-p>"
    endif
endfunction
inoremap <Tab> <c-r>=InsertTabWrapper()<cr>
inoremap <S-Tab> <c-n>

" Index ctags from any project, including those outside Rails
map <Leader>ct :!ctags -R .<CR>

" Switch between the last two files
nnoremap <Leader><Leader> <c-^>

" Get off my lawn
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>

" vim-rspec mappings
nnoremap <Leader>t :call RunCurrentSpecFile()<CR>
nnoremap <Leader>s :call RunNearestSpec()<CR>
nnoremap <Leader>l :call RunLastSpec()<CR>

" Run commands that require an interactive shell
nnoremap <Leader>r :RunInInteractiveShell<space>

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Set spellfile to location that is guaranteed to exist, can be symlinked to
" Dropbox or kept in Git and managed outside of thoughtbot/dotfiles using rcm.
set spellfile=$HOME/.vim-spell-en.utf-8.add

" Always use vertical diffs
set diffopt+=vertical

" Local config
if filereadable($HOME . "/.vim/vimrc.local")
  source ~/.vim/vimrc.local
endif

" Custom splash screen
if filereadable($HOME . "/.vim/vimrc.greeting")
  source ~/.vim/vimrc.greeting
endif

let g:ruby_indent_assignment_style = 'variable'

" Config EasyMotion
map <Leader>l <Plug>(easymotion-lineforward)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
map <Leader>h <Plug>(easymotion-linebackward)

let g:EasyMotion_startofline = 0 " keep cursor colum when JK motion

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor
endif

" Run rspec commands in a GNU Screen window
let g:rspec_command = 'SlimeSend0("bundle exec rspec {spec}\n")'

" Make easytags a little perform a bit better
let g:easytags_async=1
let g:easytags_auto_highlight=0

" Configure ALE
let g:ale_sign_warning = ''
let g:ale_sign_error = ''
let g:ale_pattern_options = {'\.html$': {'ale_enabled': 0}}
let g:ale_fixers = {
      \ 'python': ['autopep8'],
      \ 'ruby':   ['rubocop'],
      \}

" Don't do extra indenting of js and css in HTMKL files
let g:html_indent_script1 = 'zero'
let g:html_indent_style1 = 'zero'

" Pre-fill the GNU screen session for slime
let g:slime_default_config = {"sessionname": $STY, "windowname": 6}

" Base16 SpellBad is too hard to read; use WarningMsg instead
hi clear SpellBad
hi link SpellBad WarningMsg

" Use FZF for fuzzy search
nmap <Leader>p :FZF<CR>
" Convert Ruby 1.9 hash syntax to hashrocket style
vnoremap <Leader>hr :s/\(\s\+\)\(\w\+\):\s/\1:\2 => /g<CR>
" Convert Hashrocket syntax to Ruby 1.9 syntax
vnoremap <Leader>!hr :s/:\([^ ]*\)\(\s*\)=>/\1:/<CR>
" Convert Single Quotes to Double Quotes
vnoremap <Leader>' :s/"/'/g<CR>
" Add Space inside curly braces
vnoremap <Leader>{} :s/{\(\S\)\(.*\)\(\S\)}/{ \1\2\3 }/<CR>
" Add frozen_string_literal magic comment
function! FrozenStringLiteralRB()
  normal! m'
  1
  set paste
  normal! O# frozen_string_literal: true
  set nopaste
  normal! ``
endfunction
nnoremap <Leader>fsl :call FrozenStringLiteralRB()<CR>

" Deduplicate a range of lines
" must be EXACT duplicates, e.g. for
"   aaa
"   aaa
"   aaa
"   bba
"   bbb
" would delete two of the three 'aaa' lines
vnoremap <Leader>dedup :s/^\(.*$\)\(\n\1\)\+/\1/<CR>

" Create a Scratch buffer
command! Scratch new | setlocal bt=nofile bh=wipe nobl noswapfile nu
