####
# HAPPY PRIDE! 🌈
#
#
# black: #000000
# brown: #613915
# red: #e40303
# orange: #ff8c00
# yellow: #ffed00
# green: #008026
# dark blue: #24408e
# purple/violet: #732982
# light blue: #74d7ee
# white: #ffffff
# pink: #ffafc8
# format = """
# [█ ](fg:#ffafc8 bg:#ffffff)\
# [ ](fg:#ffffff bg:#74d7ee)\
# [ ](fg:#74d7ee bg:#732982)\
# [ ](fg:#732982 bg:#24408e)\
# [ ](fg:#24408e bg:#008026)\
# [ ](fg:#008026 bg:#ffed00)\
# [ ](fg:#ffed00 bg:#ff8c00)\
# [ ](fg:#ff8c00 bg:#e40303)\
# [ ](fg:#e40303 bg:#613915)\
# [ ](fg:#613915 bg:#000000)\
# [ ](fg:#000000 bg:#ffffff)\
# $username\
# [ ](fg:#ffffff bg:243)\
# $os\
# $hostname\
# [ ](fg:243 bg:245)\
# $directory\
# [ ](fg:245 bg:247)\
# $git_branch\
# $git_status\
# [ ](fg:247 bg:249)\
# $c\
# $elixir\
# $elm\
# $golang\
# $gradle\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $python\
# $ruby\
# $rust\
# $scala\
# [ ](fg:249 bg:none)\
# $line_break\
# $character
# """

format = """
[ ](fg:black bg:bright-purple)\
[ ](fg:bright-purple bg:white)\
[ ](fg:white bg:bright-blue)\
[ ](fg:bright-blue bg:purple)\
[ ](fg:purple bg:green)\
[ ](fg:green bg:bright-yellow)\
[ ](fg:bright-yellow bg:16)\
[ ](fg:16 bg:red)\
[ ](fg:red bg:white)\
$username\
[ ](fg:white bg:18)\
$hostname\

[ ](fg:18 bg:19)\
$directory\
[ ](fg:19 bg:20)\
$git_branch\
$git_status\
[ ](fg:20 bg:none)\
$line_break\
$character
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bold fg:black bg:white"
style_root = "bold fg:bright-red bg:white"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = 'fg:15 bg:18'
format = '[ $symbol]($style)'
disabled = false # Disabled by default

[hostname]
ssh_only = false
style = 'fg:7 bg:18'
format = '[ $ssh_symbol$hostname ]($style)'

[directory]
style = "fg:black bg:19"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"projects" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:black bg:20"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:black bg:20"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = ""
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:black bg:21"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "fg:black bg:yellow"
format = '[ ♥ $time ]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
